/**
 * Mapping of MDI icons to FA icons
 * - Key: the name of the icon in MDI (e.g. mdiEmail) https://pictogrammers.com/library/mdi/icon/email/
 * - Value: The name of the icon in fontawesome <package>-<icon-name> https://fontawesome.com/icons/envelope?f=classic&s=solid
 *   - Use null if the icon is not available in fontawesome, but you want it to keep in the list (the original MDI icon will be used)
*/
export default {
  icons: {
    mdiAccount: 'fas-user',
    mdiAccountCircleOutline: 'far-user-circle',
    mdiAccountGroup: 'fas-users',
    mdiAccountPlus: 'fas-user-plus',
    mdiAlertCircleOutline: 'far-exclamation-circle',
    mdiAlertOutline: 'far-exclamation-triangle',
    mdiArrowDown: 'fas-arrow-down',
    mdiArrowLeft: 'fas-arrow-left',
    mdiArrowRight: 'fas-arrow-right',
    mdiArrowUp: 'fas-arrow-up',
    mdiBackupRestore: 'fas-clock-rotate-left',
    mdiCalendarRange: 'far-calendar-range',
    mdiChartPie: 'fas-chart-pie',
    mdiCheck: 'far-check',
    mdiCheckBold: 'fas-check',
    mdiChevronDown: 'fas-chevron-down',
    mdiChevronRight: 'fas-chevron-right',
    mdiCircleOutline: 'far-circle',
    mdiCircleSlice3: 'far-circle-quarter-stroke',
    mdiClipboard: 'fas-clipboard',
    mdiClipboardFlow: 'fas-copy',
    mdiClose: 'fas-xmark',
    mdiCloud: 'fas-cloud',
    mdiCloudCheckVariant: 'fas-cloud-check',
    mdiCog: 'fas-gear-complex',
    mdiContacts: 'fas-image-user',
    mdiDelete: 'fas-trash-can',
    mdiDotsHorizontal: 'far-ellipsis',
    mdiDownload: 'fas-download',
    mdiDragVertical: 'fasr-grip-dots-vertical',
    mdiEmail: 'fas-envelope',
    mdiExclamation: 'fas-exclamation',
    mdiEye: 'fas-eye',
    mdiEyeOutline: 'far-eye',
    mdiFacebook: 'fab-facebook',
    mdiFile: 'fas-file',
    mdiFileCompare: 'fas-file-plus-minus',
    mdiFileMultiple: 'fas-files',
    mdiFileUpload: 'fas-file-arrow-up',
    mdiFilter: 'fas-filter',
    mdiFolder: 'fas-folder',
    mdiFolderOpen: 'fas-folder-open',
    mdiFormatListBulletedSquare: 'fasr-list',
    mdiFullscreen: 'fas-expand',
    mdiFullscreenExit: 'fas-compress',
    mdiHeadset: 'fas-headset',
    mdiImageEdit: null,
    mdiImageOffOutline: 'far-image-slash',
    mdiInformation: 'fas-circle-info',
    mdiKey: 'fas-key',
    mdiLink: 'fas-link',
    mdiListBox: 'fas-rectangle-list',
    mdiLock: 'fas-lock',
    mdiLockOpen: 'fas-lock-open',
    mdiMagnify: 'far-magnifying-glass',
    mdiMapClock: 'far-map-location-dot',
    mdiMapMarker: 'fas-location-dot',
    mdiMenuDown: 'fas-caret-down',
    mdiMenuUp: 'fas-caret-up',
    mdiMessageReplyText: 'fas-message-lines',
    mdiNetwork: 'fas-network-wired',
    mdiNewBox: 'fas-square-plus',
    mdiPalette: 'fas-palette',
    mdiPencil: 'fas-pen',
    mdiPlayCircle: 'fas-play',
    mdiPlayCircleOutline: 'far-play',
    mdiPlus: 'fas-plus',
    mdiQrcode: 'fas-qrcode',
    mdiRefresh: 'fas-arrow-rotate-right',
    mdiShareCircle: 'fas-share',
    mdiSourceBranch: 'fas-code-branch',
    mdiStar: 'fass-star',
    mdiStarOutline: 'fasr-star',
    mdiTag: 'fas-tag',
    mdiTrayArrowDown: 'far-arrow-down-to-bracket',
    mdiTriangleSmallDown: 'fas-caret-down',
    mdiTune: 'fas-sliders',
    mdiTwitter: 'fab-twitter',
    mdiUndo: 'fas-undo-alt',
    mdiUndoVariant: 'fas-undo',
    mdiUpload: 'fas-upload',
    mdiViewGrid: 'fas-grid',
    mdiWeatherNight: 'far-moon-stars',
    mdiWeb: 'far-globe',
    mdiWrench: 'fas-wrench',
  },
};
