/**
 * Mapping of MDI icons to FA icons
 * Mapping is done
 * by the name of the icon in MDI (e.g. mdiEmail) https://pictogrammers.com/library/mdi/icon/email/
 * to the name of the icon in fontawesome <package>-<icon-name> https://fontawesome.com/icons/envelope?f=classic&s=solid
 */
export default {
  icons: {
    mdiAccount: 'fas-user',
    mdiAccountCircleOutline: 'fas-user-circle',
    mdiAccountGroup: 'fas-users',
    mdiAccountPlus: 'fas-user-plus',
    mdiAlertCircleOutline: 'fas-exclamation-circle',
    mdiAlertOutline: 'fas-exclamation-triangle',
    mdiArrowDown: 'fas-arrow-down',
    mdiArrowLeft: 'fas-arrow-left',
    mdiArrowRight: 'fas-arrow-right',
    mdiArrowUp: 'fas-arrow-up',
    mdiBackupRestore: 'fas-undo',
    mdiCalendarRange: 'fas-calendar-alt',
    mdiChartPie: 'fas-pie-chart',
    mdiCheck: 'fas-check',
    mdiCheckBold: 'fas-question',
    mdiChevronDown: 'fas-chevron-down',
    mdiChevronRight: 'fas-chevron-right',
    mdiCircleOutline: 'fas-question',
    mdiCircleSlice3: 'fas-question',
    mdiClipboard: 'fas-clipboard',
    mdiClipboardFlow: 'fas-copy',
    mdiClose: 'fas-close',
    mdiCloudCheckVariant: 'fas-cloud-check',
    mdiCog: 'fas-cog',
    mdiContacts: 'fas-address-book',
    mdiDelete: 'fas-trash',
    mdiDotsHorizontal: 'fas-ellipsis-h',
    mdiDownload: 'fas-download',
    mdiDragVertical: 'fas-grip-lines-vertical',
    mdiEmail: 'fas-envelope',
    mdiExclamation: 'fas-exclamation',
    mdiEye: 'fas-eye',
    mdiEyeOutline: 'fas-question',
    mdiFacebook: 'fas-facebook',
    mdiFile: 'fas-file',
    mdiFileCompare: 'fas-question',
    mdiFileMultiple: 'fas-question',
    mdiFileUpload: 'file-arrow-up',
    mdiFilter: 'fas-filter',
    mdiFolder: 'fas-folder',
    mdiFolderOpen: 'fas-folder-open',
    mdiFormatListBulletedSquare: 'fas-list-ul',
    mdiFullscreen: 'fas-maximize',
    mdiFullscreenExit: 'fas-minimize',
    mdiImageEdit: 'fas-question',
    mdiImageOffOutline: 'fas-question',
    mdiInformation: 'fas-info-circle',
    mdiKey: 'fas-key',
    mdiLink: 'fas-link',
    mdiListBox: 'fas-rectangle-list',
    mdiLock: 'fas-lock',
    mdiLockOpen: 'fas-unlock',
    mdiMagnify: 'fas-search',
    mdiMapClock: 'fas-question',
    mdiMapMarker: 'fas-map-marker-alt',
    mdiMenuDown: 'fas-angle-down',
    mdiMenuUp: 'fas-angle-up',
    mdiMessageReplyText: 'fas-reply',
    mdiNetwork: 'fas-network-wired',
    mdiNewBox: 'fas-question',
    mdiPalette: 'fas-palette',
    mdiPencil: 'fas-pencil-alt',
    mdiPlayCircle: 'fas-play-circle',
    mdiPlayCircleOutline: 'far-play-circle',
    mdiPlus: 'fas-plus',
    mdiQrcode: 'fas-qrcode',
    mdiRefresh: 'fas-arrow-rotate-right',
    mdiShareCircle: 'fas-share',
    mdiSourceBranch: 'fas-code-branch',
    mdiStar: 'fas-star',
    mdiStarOutline: 'fas-star-o',
    mdiTag: 'fas-tag',
    mdiTrayArrowDown: 'fas-question',
    mdiTriangleSmallDown: 'fas-caret-down',
    mdiTune: 'fas-sliders-h',
    mdiTwitter: 'fas-twitter',
    mdiUndo: 'fas-undo',
    mdiUndoVariant: 'fas-undo',
    mdiUpload: 'fas-upload',
    mdiViewGrid: 'fas-question',
    mdiWeatherNight: 'fas-cloud-moon',
    mdiWeb: 'fas-globe',
    mdiWrench: 'fas-wrench',
  },
};
