/**
 * Mapping of MDI icons to FA icons
 * Mapping is done
 * by the name of the icon in MDI (e.g. mdiEmail) https://pictogrammers.com/library/mdi/icon/email/
 * to the name of the icon in fontawesome <package>-<icon-name> https://fontawesome.com/icons/envelope?f=classic&s=solid
 */
export default {
  icons: {
    mdiAccount: 'fas-user',
    mdiAccountCircleOutline: 'far-user-circle',
    mdiAccountGroup: 'fas-users',
    mdiAccountPlus: 'fas-user-plus',
    mdiAlertCircleOutline: 'fasr-exclamation-circle',
    mdiAlertOutline: 'fasr-exclamation-triangle',
    mdiArrowDown: 'fasr-arrow-down',
    mdiArrowLeft: 'fasr-arrow-left',
    mdiArrowRight: 'fasr-arrow-right',
    mdiArrowUp: 'fasr-arrow-up',
    mdiBackupRestore: 'fass-clock-rotate-left',
    mdiCalendarRange: 'far-calendar-range',
    mdiChartPie: 'fass-pie-chart',
    mdiCheck: 'fasr-check',
    mdiCheckBold: 'fass-check',
    mdiChevronDown: 'fasr-chevron-down',
    mdiChevronRight: 'fasr-chevron-right',
    mdiCircleOutline: 'far-circle',
    mdiCircleSlice3: 'fasr-circle-quarter-stroke',
    mdiClipboard: 'fas-clipboard',
    mdiClipboardFlow: 'fas-clipboard',
    mdiClose: 'fasr-close',
    mdiCloudCheckVariant: 'fas-cloud-check',
    mdiCog: 'fass-cog',
    mdiContacts: 'fas-image-user',
    mdiDelete: 'fas-trash',
    mdiDotsHorizontal: 'far-ellipsis',
    mdiDownload: 'fass-down-to-line',
    mdiDragVertical: 'fass-grip-vertical',
    mdiEmail: 'fas-envelope',
    mdiExclamation: 'fasr-exclamation',
    mdiEye: 'fass-eye',
    mdiEyeOutline: 'fasr-eye',
    mdiFacebook: 'fab-facebook',
    mdiFile: 'fas-file',
    mdiFileCompare: 'fas-file-plus-minus',
    mdiFileMultiple: 'fas-files',
    mdiFileUpload: 'fas-file-arrow-up',
    mdiFilter: 'fas-filter',
    mdiFolder: 'fas-folder',
    mdiFolderOpen: 'fas-folder-open',
    mdiFormatListBulletedSquare: 'fasr-list',
    mdiFullscreen: 'fass-expand',
    mdiFullscreenExit: 'fass-compress',
    mdiImageEdit: 'fas-file-signature',
    mdiImageOffOutline: 'far-image-slash',
    mdiInformation: 'fass-info-circle',
    mdiKey: 'fass-key-skeleton',
    mdiLink: 'fasr-link-simple',
    mdiListBox: 'fas-rectangle-list',
    mdiLock: 'fas-lock-keyhole',
    mdiLockOpen: 'fas-lock-keyhole-open',
    mdiMagnify: 'fasr-magnifying-glass',
    mdiMapClock: 'far-map-location-dot',
    mdiMapMarker: 'fass-map-marker-alt',
    mdiMenuDown: 'fass-caret-down',
    mdiMenuUp: 'fass-caret-up',
    mdiMessageReplyText: 'fas-message-lines',
    mdiNetwork: 'fas-network-wired',
    mdiNewBox: 'fas-square-star',
    mdiPalette: 'fas-palette',
    mdiPencil: 'fas-pen',
    mdiPlayCircle: 'fass-play-circle',
    mdiPlayCircleOutline: 'fasr-play-circle',
    mdiPlus: 'fass-plus',
    mdiQrcode: 'fass-qrcode',
    mdiRefresh: 'fass-rotate-right',
    mdiShareCircle: 'far-share',
    mdiSourceBranch: 'fas-code-branch',
    mdiStar: 'fass-star',
    mdiStarOutline: 'fasr-star',
    mdiTag: 'fas-tag',
    mdiTrayArrowDown: 'far-arrow-down-to-bracket',
    mdiTriangleSmallDown: 'fass-caret-down',
    mdiTune: 'fasr-sliders',
    mdiTwitter: 'fab-twitter',
    mdiUndo: 'fass-undo-alt',
    mdiUndoVariant: 'fass-undo',
    mdiUpload: 'fass-up-from-line',
    mdiViewGrid: 'fass-grid-2',
    mdiWeatherNight: 'far-moon-stars',
    mdiWeb: 'far-globe',
    mdiWrench: 'fass-wrench',
  },
};
